type: object

additionalProperties: false
description: |
  Summarize this object's scope & function.
required:
  - pageSize
  - page
  - products
properties:
  pageSize:
    type: integer
    
    minimum: 1
    description: |
      Describe this data member. Internal.
  page:
    type: integer
    
    minimum: 0
    description: |
      Describe this data member. Internal.
  start:
    type: string
    format: date-time
    description: |
      Describe this data member.
  end:
    type: string
    format: date-time
    description: |
      Describe this data member.
  products:
    type: array
    
    uniqueItems: true
   
    minItems: 0
    description: |
      Describe this data member.
    items:
      $ref: product-summary.yaml
  links:
    $ref: links.yaml
