type: object

additionalProperties: false
description: |
  Summarize this object's scope & function.
required:
  - productId
  - productName
  - productType
  - productStatus
  - productDescription
properties:
  productId:
    type: string
    
    minLength: 1
    description: |
      Describe this data member.
  productName:
    type: string
    
    minLength: 1
    description: |
      Describe this data member.
  productType:
    type: string
    
    minLength: 1
    description: |
      Description mentions each supported literal value such as `GA` or `BETA`, or else links to an [external table](ref:enum-tbl) whose doc serves out from 
    
    
    enum:
      $ref: enum-productType.yaml
  productStatus:
    type: string
    description: |
      Description mentions each supported literal value such as `GA` or `BETA`, or else links to an [external table](ref:enum-tbl) whose doc serves out from 
    
    
    enum:
      $ref: enum-productStatus.yaml
  productDescription:
    type: string
    
    minLength: 1
    description: |
      Describe this data member.
  modifiedTime:
    $ref: modifiedTime.yaml
  modifiedBy:
    $ref: modifiedBy.yaml
  createdTime:
    $ref: createdTime.yaml
  createdBy:
    $ref: createdBy.yaml
  
  
  
  productGuid:
    type: string
    
    minLength: 1
    description: |
      Describe this data member. Internal.
  links:
    $ref: links.yaml
