openapi: 3.0.0
info:
  title: Customers
  version: v1
servers:
  - url: https://{hostname}/commerce/v1
paths:
  /customers:
    get:
      operationId: get-customers
      summary: List of customers
      tags:
        - Customers
      description: |
        Describe what the operation does here.
      parameters:
        - $ref: parameters/view-query.yaml
        - $ref: parameters/filter-query.yaml
        - $ref: parameters/sortBy-query.yaml
        - $ref: parameters/page-query.yaml
        - $ref: parameters/pageSize-query.yaml
      responses:
        200:     
          content:  
            application/json:
              example:
                $ref: examples/customers.json
              schema:
                $ref: schemas/customers.yaml
          description: |
            The response provides the collection of `customers`.
               
        400:
          $ref: errors/400.yaml
       