type: object
# This specifies: only the defined set of 'properties' are valid:
additionalProperties: false
description: |
  Summarize this object's scope & function.
required:
  - productId
  - productName
  - productType
  - productStatus
  - productDescription
properties:
  productId:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Describe this data member.
  productName:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Describe this data member.
  productType:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Description mentions each supported literal value such as `GA` or `BETA`, or else links to an [external table](ref:enum-tbl) whose doc serves out from techdocs.akamai.com.
    # Link a common set of enum values to ensure consistency across
    # all schemas
    enum:
      $ref: enum-productType.yaml
  productStatus:
    type: string
    description: |
      Description mentions each supported literal value such as `GA` or `BETA`, or else links to an [external table](ref:enum-tbl) whose doc serves out from techdocs.akamai.com.
    # Link a common set of enum values to ensure consistency across
    # all schemas
    enum:
      $ref: enum-productStatus.yaml
  productDescription:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Describe this data member.
  modifiedTime:
    $ref: modifiedTime.yaml
  modifiedBy:
    $ref: modifiedBy.yaml
  createdTime:
    $ref: createdTime.yaml
  createdBy:
    $ref: createdBy.yaml
  # Example of internal or pre-release data member the
  # `_publication.yaml` config file sets to `exclude` from
  # publication/distribution.
  productGuid:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Describe this data member. Internal.
  links:
    $ref: links.yaml
