type: object
# This specifies: only the defined set of 'properties' are valid:
additionalProperties: false
# If allowing JSON merge PATCH requests, this means you have to specify
# at least one field to modify.
minProperties: 1
description: |
  Summarize this object's scope & function.
properties:
  productName:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Describe this data member.
  productType:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Description mentions each supported literal value such as `GA` or `BETA`, or else links to an [external table](ref:enum-tbl) whose doc serves out from techdocs.akamai.com.
    enum:
      # The first `INTERNAL` enum value is an example of an internal
      # or pre-release enum value the `_publication.yaml` file sets to
      # `exclude` from publication and distribution. Since it's
      # difficult to reliably express an array location as a JSON
      # Pointer expression, recommend positioning any items to
      # suppress at the start of the array.
      - INTERNAL
      - STANDARD
      - SPECIAL
      - ONLINE
  productDescription:
    type: string
    # minLength:0 if the string can be empty (""); otherwise 1 or more
    minLength: 1
    description: |
      Describe this data member.
