name: Swagger Validation

on:
  push:
    branches: [ master ]

jobs:
  validate-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Install Swagger Validator
        run: npm install -g swagger-cli
      - name: Validate Swagger
        run: swagger-cli validate swg.openapi.yaml
